### ISSUE TITLE
Update app bar color on theme change 

### ISSUE THREAD

**Issue by wkramer** [Deltares/fews-web-oc#655]
When the use switches the theme from light to dark (or vice versa) the app bar color should be updated.

This can happen when different values are provide for light and dark:

```css
:root {
  --weboc-app-bar-bg-color: rgb(249, 225, 30);
}

.dark {
  --weboc-app-bar-bg-color: none;
}
```
